package moduls.entitys;
// Generated 13.08.2021 16:05:29 by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * Searchforaggregator generated by hbm2java
 */
@Entity
@Table(name="searchforaggregator"
    ,catalog="taxicomp"
)
public class Searchforaggregator  implements java.io.Serializable {


     private int idOrderForAggregator;
     private Aggregator aggregator;
     private Order order;
     private Integer price;
     private Byte reserved;

    public Searchforaggregator() {
    }

	
    public Searchforaggregator(int idOrderForAggregator, Aggregator aggregator, Order order) {
        this.idOrderForAggregator = idOrderForAggregator;
        this.aggregator = aggregator;
        this.order = order;
    }
    public Searchforaggregator(Aggregator aggregator, Order order, Integer price) {
       this.aggregator = aggregator;
       this.order = order;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="idOrderForAggregator", unique=true, nullable=false)
    public int getIdOrderForAggregator() {
        return this.idOrderForAggregator;
    }
    
    public void setIdOrderForAggregator(int idOrderForAggregator) {
        this.idOrderForAggregator = idOrderForAggregator;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAggregator", nullable=false)
    public Aggregator getAggregator() {
        return this.aggregator;
    }
    
    public void setAggregator(Aggregator aggregator) {
        this.aggregator = aggregator;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idOrder", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="Price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

    
    @Column(name="Reserved")
    public Byte getReserved() {
        return this.reserved;
    }
    
    public void setReserved(Byte reserved) {
        this.reserved = reserved;
    }




}


