package moduls.entitys;
// Generated 13.08.2021 16:05:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="taxicomp"
)
public class User  implements java.io.Serializable {


     private int idUser;
     private String name;
     private String login;
     private String pass;
     private Set<Order> orders = new HashSet<Order>(0);

    public User() {
    }

	
    public User(int idUser) {
        this.idUser = idUser;
    }
    public User(int idUser, String name, String login, String pass, Set<Order> orders) {
       this.idUser = idUser;
       this.name = name;
       this.login = login;
       this.pass = pass;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="idUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Login", length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="Pass", length=45)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


